spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/evs}
    username: ${DB_USER:evs}
    password: ${DB_PASSWORD:evs}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
