CREATE TABLE diseases (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description TEXT NULL
);

CREATE TABLE vaccines (
    id UUID PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    manufacturer VARCHAR(255) NULL,
    validity_days INTEGER NOT NULL,
    doses_required INTEGER NOT NULL,
    days_between INTEGER NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE vaccine_diseases (
    vaccine_id UUID NOT NULL,
    disease_id INTEGER NOT NULL,
    PRIMARY KEY (vaccine_id, disease_id),
    CONSTRAINT fk_vaccine_diseases_vaccine FOREIGN KEY (vaccine_id) REFERENCES vaccines(id),
    CONSTRAINT fk_vaccine_diseases_disease FOREIGN KEY (disease_id) REFERENCES diseases(id)
);
